### create request as current signed user to mate with id
POST http://localhost:3000/mates/requests/2 HTTP/1.1
Content-Type: application/json

{
  "location": "yangon",
  "time": "2022-10-12 09:00:00",
  "duration": "03:00",
  "price": 15000,
  "specialRequest": "some requests"
}

### accept request with id
PATCH  http://localhost:3000/mates/requests/accept/2 HTTP/1.1
Content-Type: application/json

{
  "accepted": true
}

### Get all reuquset for current mate
GET http://localhost:3000/mates/requests HTTP/1.1