### get all appointements of current mate
GET http://localhost:3000/mates/appointments HTTP/1.1

### change completion with appintments id
PATCH  http://localhost:3000/mates/appointments/3 HTTP/1.1
Content-Type: application/json

{
  "completed": true
}


### get all completd appointments of current mate
GET http://localhost:3000/mates/appointments/completed HTTP/1.1
