### create new user
POST http://localhost:3000/users/signup HTTP/1.1
Content-Type: application/json

{
  "userName": "user name",
  "email": "asdf@asdf.com",
  "phone": "+9599999999",
  "password": "mypassword"
}

### signIn as existing user
POST http://localhost:3000/users/signin HTTP/1.1
Content-Type: application/json

{
  "email": "asdf@asdf.com",
  "password": "mypassword"
}

### signOut user
POST http://localhost:3000/users/signout HTTP/1.1

### delete current signed user
DELETE http://localhost:3000/users/delete HTTP/1.1

### who am i
GET  http://localhost:3000/users/whoami HTTP/1.1


### Update current signed user
PATCH  http://localhost:3000/users/update HTTP/1.1
Content-Type: application/json

{
  "userName": "hello"
}

### Get Sessioin
GET http://localhost:3000/users/session HTTP/1.1