### create new mate
POST http://localhost:3000/mates/signup HTTP/1.1
Content-Type: application/json

{
  "name": "mate name",
  "email": "asdf@asdf.com",
  "password": "mypassword",
  "phone": "+959000000000",
  "photoUrl": "http://photo.com/photo.png",
  "city": "yangon",
  "gender": "male",
  "age": 26,
  "height": 170,
  "bodyType": "slim",
  "language": "Myanmar",
  "service": "cooking, washing",
  "time": "03:00",
  "responseTime": "01:00"
}

### sign in as existing mate
POST http://localhost:3000/mates/signin HTTP/1.1
Content-Type: application/json

{
  "email": "asdf@asdf.com",
  "password": "mypassword"
}

### sign out mate
POST  http://localhost:3000/mates/signout HTTP/1.1

### delete current  signed mate account
DELETE  http://localhost:3000/mates/delete HTTP/1.1

#### who am i
GET   http://localhost:3000/mates/whoami HTTP/1.1


### update a mate
PATCH  http://localhost:3000/mates/update HTTP/1.1
Content-Type: application/json

{
  "name": "new name"
}

### change current signed mate active status
PATCH  http://localhost:3000/mates/active-status HTTP/1.1
Content-Type: application/json

{
  "online": true
}
